package com.example.cysafecampus.model;

import java.io.Serializable;

/**
 * Represents an event generated by a sensor.
 * Carries all context needed for AdminAgent to make decisions:
 * what happened, how severe, and where.
 */
/**
 * Represents an event produced by a sensor within the building model.
 *
 * <p>Each SensorEvent carries:
 * <ul>
 *   <li>a {@link SensorEventType} describing the kind of event detected;</li>
 *   <li>a severity level (integer from 1 = low to 5 = critical) used by agents
 *       (for example {@code AdminAgent}) to decide whether to escalate or notify
 *       supervisors;</li>
 *   <li>the {@link BuildingElement} where the event was detected;</li>
 *   <li>a timestamp (milliseconds since the epoch) captured at construction time
 *       via {@link System#currentTimeMillis()}.</li>
 * </ul>
 *
 * <p>This class implements {@link java.io.Serializable} so events can be serialized
 * for transmission or persistence. Instances are initialized via the constructor
 * and expose read-only accessors for their properties.
 *
 * <p>Examples:
 * <pre>
 * SensorEvent e = new SensorEvent(SensorEventType.FIRE, 5, someBuildingElement);
 * System.out.println(e.getTimestamp()); // construction time in ms
 * </pre>
 *
 * @see SensorEventType
 * @see BuildingElement
 * @since 1.0
 */
public class SensorEvent implements Serializable {

    /** Type of event detected */
    private SensorEventType type;

    /**
     * Severity level from 1 (low) to 5 (critical).
     * Used by AdminAgent to decide whether to notify supervisors.
     */
    private int severity;

    /** The building element where the event was detected */
    private BuildingElement location;

    /** Timestamp of the event (simulation tick or system time) */
    private long timestamp;

    /**
     * Constructor for SensorEvent.
     * @param type the type of event
     * @param severity severity from 1 to 5
     * @param location the building element concerned
     */
    public SensorEvent(SensorEventType type, int severity, BuildingElement location) {
        this.type = type;
        this.severity = severity;
        this.location = location;
        this.timestamp = System.currentTimeMillis();
    }

    public SensorEventType getType() { return type; }
    public int getSeverity() { return severity; }
    public BuildingElement getLocation() { return location; }
    public long getTimestamp() { return timestamp; }

    @Override
    public String toString() {
        return "[" + type + " | severity=" + severity + " | location=" + location.getName() + "]";
    }
}
